version: '3.5'
services:
  app:
    container_name: live_qa_service
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    command: "./init.sh"
    ports:
      - "7000:3000"

networks:
  default:
    external:
      name: schoolar-network

