version: '3.5'
services:
  app:
    container_name: live_qa
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: schoolar-network

